version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: curl -k -u $FITOXSUID:$FITOXSTOKEN --request POST -H "Content-Type:application/json" -d '{"pit":"310","targetid":"izXMpQXpCDJXBqkzjbkD1618540367","ci":"Circle CI","tipo":"6"}' https://fitoxs.com/ScanTarget/

